# Generated by Django 3.1.6 on 2021-02-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('company', models.CharField(max_length=95)),
                ('id_number', models.CharField(blank=True, max_length=255)),
                ('telephone_number', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
